### ISSUE TITLE
Can you add python-3.6 to your test targets

### ISSUE THREAD

**Issue by dol-sen** [rutsky/setuptools-trial#12]
Buildbot has enabled testing on 3.6 and this is one of the deps.
Also at my work they are going to move from 3.4 soon, and go to 3.6, skipping 3.5

Thank you

**Comment by rutsky** [comment]
@dol-sen sorry for the long response, Python 3.6 already in the setuptools-trial tests configuration: both in tox and Travis configurations.

**Comment by rutsky** [comment]
@dol-sen feel free to reopen this issue if you think it is not resolved.

**Comment by dol-sen** [comment]
OK, thank you.  it turned out that I was working on the latest release and browsing the files at that release commit.  I wasn't at HEAD.  That one did not have 3.6 enabled at that time.
